# vi: syntax=sh

# Settings for SVN version of NEMO (4.0 versions)
export PACKAGE_VERSIONS="nemo:4.0.7"
export NEMO_CFG="ORCA2"
export NEMO_SUBCOMPONENTS="OCE ICE"
export NEMO_KEYS_TO_DELETE="key_top"
export NEMO_KEYS_TO_ADD="key_netcdf4 key_mpp_mpi key_iomput"
export NEMO_WORKLOAD_ARCHIVE="ORCA2_ICE_v4.0.tar"
export NEMO_WORKLOAD_MD5="fe6c0c2ae1d4fb42b30578646536615f"


# Settings for github version of NEMO (4.2 versions)
# TBD


